services:
  postgres:
    image: postgres:15-alpine
    container_name: fitness_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sami          # Add this line
      POSTGRES_PASSWORD: example
      POSTGRES_DB:  
     
    ports:
      - "5432:5432"
    
   
   
    command: >
      postgres -c listen_addresses='*'
               -c log_statement=all

  redis:
    image: redis:7-alpine
    container_name: fitness_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fitness_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: samimh23@fitness.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: